Team a
blockchain-java-team/blockchain pull request #5
Opened 2024-11-16 00:58 UTC by Adamo08

Pull request

2024-11-16 01:10 UTC, hakkm requested changes

2024-11-16 01:10 UTC, hakkm commented on src/main/java/com/blockchain/model/Transaction.java
> +public class Transaction implements Serializable {
here remove Serializable

2024-11-16 01:10 UTC, hakkm commented on src/main/java/com/blockchain/model/Transaction.java
> +@Setter
also here add a lambok @Setter for each att that needs it

2024-11-16 01:10 UTC, hakkm commented on src/main/java/com/blockchain/model/Transaction.java
> +    private String fromFX;
For example this one don't need a setter

2024-11-16 01:11 UTC, hakkm commented
please do the changes, and if you have any ideas, i'm open to discuss them

2024-11-16 01:45 UTC, Adamo08 commented
> please do the changes, and if you have any ideas, i'm open to discuss them

I have reviewed and implemented the suggested changes. The issues pointed out have been addressed, and the necessary adjustments have been made. Please let me know if any further modifications are needed.

2024-11-16 18:14 UTC, hakkm commented on src/test/java/com/blockchain/model/Transaction.java
Can you move this to src/main

2024-11-16 18:15 UTC, hakkm commented on src/main/java/com/blockchain/model/Transaction.java
> +import java.io.Serializable;
we don't need Serializable for now

2024-11-17 12:22 UTC, Adamo08 commented on src/main/java/com/blockchain/model/Transaction.java
> +public class Transaction implements Serializable {
Done

2024-11-17 12:32 UTC, Adamo08 commented on src/test/java/com/blockchain/model/Transaction.java
Thanks for catching that! I've moved Transaction.java to src/main in the latest commit.

2024-11-17 16:29 UTC, closed without merging